---
- name: Gather_facts Variable Example
  hosts: nodes
  tasks:


    # display the variable data type
    - debug:
        msg:
          - " Data type of 'ansible_architecture'  is {{ ansible_architecture | type_debug }} "
          - " Data type of 'ansible_apparmor' is {{ ansible_apparmor | type_debug }} "
          - " Data type of 'ansible_all_ipv4_addresses' is {{ ansible_all_ipv4_addresses | type_debug }} "

    # Simply printing the value of fact which is Ansible UnSafe Text type
    - debug:
        msg: "{{ ansible_architecture }}"


    # Accessing an element of dictionary
    - debug:
        msg: "{{ansible_memory_mb}}"

    # Accessing the list
    - debug:
        msg: "{{ansible_all_ipv4_addresses}}"

    # Accessing the Second Element of the list
    - debug:
        msg: "{{ansible_memory_mb['real']}}"

    # Accessing the third Element of the list
    - debug:
        msg: "{{ansible_memory_mb['swap']}}"

    # Execute Host based task using variable
    - name: Execute the command only node2
      shell: "uname -a"
      when: ansible_hostname == 'node2'
      register: out
      tags: out

    - debug: msg="{{out}}"
