all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
nodes:
  hosts:
    node1:
      ansible_host: debnode1ovh
web:
  hosts:
    node2:
      ansible_host: 51.195.233.6
