---

-
  name: "Installation Apache utilisant docker"
  hosts: all
  become: true
  vars:
    ansible_become_pass: '{{sshpass}}'
  pre_tasks:
     - name: install python-pip
       apt: name=python3-pip state=present update_cache=yes
     - name: Install docker python
       pip: name=docker-py
  tasks:
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
