---

-
  name: "Installation Apache utilisant docker"
  hosts: all
  tasks:
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
